### ISSUE TITLE
ABAC enforcement discrepancies

### ISSUE THREAD

**Issue by landau** [php-casbin/php-casbin#158] opened 2024-08-28 14:56 UTC
HI! Thanks for the support of this library/tool!

I have experienced an issue where an ABAC policy ignores the object and/or action when enforcing a policy. The issue arises, at least, when adding a policy using `||`, i.e. `r.sub.value == "allow" || r.sub.value == "yes"`. This issue does not occur when using the Casbin editor ([example]( https://editor.casbin.org/#B8US52KMQ)).

```php 
// ---- PHP UNIT

     $model = <<<EOT
        [request_definition]
        r = sub, obj, act

        [policy_definition]
        p = sub_rule, obj, act

        [policy_effect]
        e = some(where (p.eft == allow))

        [matchers]
        m = eval(p.sub_rule) && r.obj == p.obj && r.act == p.act
        EOT;

        // This works because each part is added as a separate policy.
        $e = new CasbinEnforcer();
        $e->setModel(Model::newModelFromString($model));
        $e->addPolicies([
            ['r.sub.value == "allow"', 'data', 'READ'],
            ['r.sub.value == "yes"', 'data', 'READ'],
        ]);
        $this->assertTrue($e->enforce((object)['value' => 'allow'], 'data', 'READ'));
        $this->assertTrue($e->enforce((object)['value' => 'yes'], 'data', 'READ'));
        $this->assertFalse($e->enforce((object)['value' => 'yes'], 'unknown_object', 'READ'));
        $this->assertFalse($e->enforce((object)['value' => 'allow'], 'unknown_object', 'READ'));
        $this->assertFalse($e->enforce((object)['value' => 'yes'], 'data', 'unknown_action'));
        $this->assertFalse($e->enforce((object)['value' => 'allow'], 'data', 'unknown_action'));

        // This works only because the policy is wrapped in parenthesis.
        $e = new CasbinEnforcer();
        $e->setModel(Model::newModelFromString($model));
        $e->addPolicies([
            ['(r.sub.value == "allow" || r.sub.value == "yes")', 'data', 'READ'],
        ]);
        $this->assertTrue($e->enforce((object)['value' => 'allow'], 'data', 'READ'));
        $this->assertTrue($e->enforce((object)['value' => 'yes'], 'data', 'READ'));
        $this->assertFalse($e->enforce((object)['value' => 'yes'], 'unknown_object', 'READ'));
        $this->assertFalse($e->enforce((object)['value' => 'yes'], 'data', 'unknown_action'));
        $this->assertFalse($e->enforce((object)['value' => 'allow'], 'unknown_object', 'READ'));
        $this->assertFalse($e->enforce((object)['value' => 'allow'], 'data', 'unknown_action'));

        // Combining using `||` does not work properly when value = "allow"
        $e = new CasbinEnforcer();
        $e->setModel(Model::newModelFromString($model));
        $e->addPolicies([
            ['r.sub.value == "allow" || r.sub.value == "yes"', 'data', 'READ'],
        ]);
        $this->assertTrue($e->enforce((object)['value' => 'allow'], 'data', 'READ'));
        $this->assertTrue($e->enforce((object)['value' => 'yes'], 'data', 'READ'));
        // These 2 tests pass
        $this->assertFalse($e->enforce((object)['value' => 'yes'], 'unknown_object', 'READ'));
        $this->assertFalse($e->enforce((object)['value' => 'yes'], 'data', 'unknown_action'));
        // [HERE IS THE ISSUE] These 2 calls are returning `true`. 
        // Why is the enforcer failing to enforce when value is "allow"?
        $this->assertFalse($e->enforce((object)['value' => 'allow'], 'unknown_object', 'READ'));
        $this->assertFalse($e->enforce((object)['value' => 'allow'], 'data', 'unknown_action'));
```
If I execute `$e->enforceEx((object)['value' => 'allow'], 'unknown_object', 'READ')` which should return false, I see.
```
array(2) {
  [0]=>
  bool(true)
  [1]=>
  array(3) {
    [0]=>
    string(46) "r.sub.value == 'allow' || r.sub.value == 'yes'"
    [1]=>
    string(4) "data"
    [2]=>
    string(4) "READ"
  }
}
```

This seems like a bug since it works in the Casbin editor. Thoughts?

**Comment by Dobmod** [comment] 2024-08-31 09:47
This is a problem caused by improper handling of expression operator precedence in the internal `eval` function.If you add parentheses in the conditional expression, for example: `p, (r.sub.value == "allow" || r.sub.value == "yes"), data, READ`, this will work well.This issue will be fixed later.😀

**Closed as completed** 2024-09-06 16:47 UTC
Labels: released
